// Code generated by MockGen. DO NOT EDIT.
// Source: temp.go

// Package temp is a generated GoMock package.
package temp

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// DoSomethingTemp mocks base method.
func (m *MockRepository) DoSomethingTemp(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoSomethingTemp", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DoSomethingTemp indicates an expected call of DoSomethingTemp.
func (mr *MockRepositoryMockRecorder) DoSomethingTemp(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoSomethingTemp", reflect.TypeOf((*MockRepository)(nil).DoSomethingTemp), arg0)
}
