run:
  concurrency: 4
  timeout: 3m
  skip-dirs:
    - utils

linters:
  enable:
    - bodyclose
    - contextcheck
    - cyclop
    - depguard
    - dogsled
    - dupl
    - errorlint
    - funlen
    - gocognit
    - gocritic
    - gocyclo
    - gofmt
    - gosec
    - lll
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - prealloc
    - predeclared

output:
  format: colored-line-number
  sort-results: false