auth:
  error:
    status: 401
    message: unauthorized

  confirmation_email:
    generate_token:
      error:
        status: 500
        message: internal server error

    task_id_conflict:
      error:
        status: 429
        message: retry again later
  signup:
    email_taken:
      error:
        status: 400
        message: email is already taken